//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 12:10:30 PM COT 
//

package co.com.bancodebogota.dtos.account.debitcards;

import java.io.Serializable;

import javax.validation.constraints.NotNull;

public class AccountToAssociateCardRequestDTO implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String documentNumber;

	private String networkOwner;

	private String cardId;

	private String cardType;

	private String cardSeqNum;

	private String fIDebitTrnNum;
	
	@NotNull
	private String productCode;

	private String acctType;

	private String acctId;

	private String trnSrc;

	private String terminalId;

	private String branchId;

	private String fullName;

	private String codeDane;

	public String getDocumentNumber() {
		return documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	public String getNetworkOwner() {
		return networkOwner;
	}

	public void setNetworkOwner(String networkOwner) {
		this.networkOwner = networkOwner;
	}

	public String getCardId() {
		return cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public String getCardType() {
		return cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public String getCardSeqNum() {
		return cardSeqNum;
	}

	public void setCardSeqNum(String cardSeqNum) {
		this.cardSeqNum = cardSeqNum;
	}

	public String getfIDebitTrnNum() {
		return fIDebitTrnNum;
	}

	public void setfIDebitTrnNum(String fIDebitTrnNum) {
		this.fIDebitTrnNum = fIDebitTrnNum;
	}

	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getAcctType() {
		return acctType;
	}

	public void setAcctType(String acctType) {
		this.acctType = acctType;
	}

	public String getAcctId() {
		return acctId;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	public String getTrnSrc() {
		return trnSrc;
	}

	public void setTrnSrc(String trnSrc) {
		this.trnSrc = trnSrc;
	}

	public String getTerminalId() {
		return terminalId;
	}

	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}

	public String getBranchId() {
		return branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	@Override
	public String toString() {
		return "AccountToAssociateCardRequestDTO [documentNumber=" + documentNumber + ", networkOwner=" + networkOwner
				+ ", cardId=" + cardId + ", cardType=" + cardType + ", cardSeqNum=" + cardSeqNum + ", fIDebitTrnNum="
				+ fIDebitTrnNum + ", productCode=" + productCode + ", acctType=" + acctType + ", acctId=" + acctId
				+ ", trnSrc=" + trnSrc + ", terminalId=" + terminalId + ", branchId=" + branchId + "]";
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getCodeDane() {
		return codeDane;
	}

	public void setCodeDane(String codeDane) {
		this.codeDane = codeDane;
	}

}
